; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = nrf24 = https://github.com/nRF24/RF24.git
monitor_speed = 115200
src_filter = +<*> -<Examples/>


[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = nrf24 = https://github.com/nRF24/RF24.git
src_filter = +<*> -<Examples/>


[env:pimoroni_pga2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pimoroni_pga2350
framework = arduino
src_filter = +<*> -<Examples/>

board_build.core = earlephilhower
board_upload.maximum_size = 8388608
board_build.filesystem_size = 2m
board_upload.psram_length = 2097152
build_flags = 
    -DRP2350_PSRAM_CS=47
    -DBUILTIN_LED_PIN=39
monitor_speed = 115200
upload_protocol = picotool
lib_deps = nrf24 = https://github.com/nRF24/RF24.git